### ISSUE TITLE
10k fix

### ISSUE THREAD

**Issue by Bandit1337** [tzechco/roblox-scripts#5]
Add 10k fix https://github.com/LukeDXD/PlsDonateNew/commit/7a8d0b2dac2a80936e4f0ec60f4049bdafd20bb8

**Comment by tzechco** [comment]
What's wrong with 10k? I'm making a rewrite of the script and could add it there.

**Comment by Bandit1337** [comment]
if over 10k it give out tags

with 10k fix
![dasdasds](https://user-images.githubusercontent.com/38169433/194729697-a68d1f78-d0b8-40f8-8004-e152cf573092.png)

without 10k fix
![asdfsdfsd](https://user-images.githubusercontent.com/38169433/194729702-ff896fce-06c0-4c3f-adf0-68c731987b28.png)

**Comment by tzechco** [comment]
Oh, I've always had issues with anything over 1k because of Roblox censoring numbers, I'll add a fix in the next update.
